name: Static Analysis

on:
  pull_request:
    paths:
      - '**.php'
      - '**.json'
      - '**.yml'

jobs:
  static-analysis:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        php: ["7.4", "8.0", "8.1"]
        composer_version: [2]
        include:
          - php: "7.2"
            composer_version: 1
          - php: "7.3"
            composer_version: 1

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "${{ matrix.php }}"
          version: "${{ matrix.composer_version }}"

      - name: Check Code Style
        uses: php-actions/composer@v6
        with:
          command: "style:check"
          php_version: "${{ matrix.php }}"
          version: "${{ matrix.composer_version }}"
